/**
 * Build: bundle the host half as plain ESM and the browser half as a CJS
 * bundle wrapped in the DSH client ModuleLoader contract
 * (`window.__ModuleLoader__.load({ id, factory: (require) => ... })`).
 *
 * Why not the upstream build? Upstream uses the monorepo-private
 * `shared/tsdown.client.ts` preset, which is not published and cannot be
 * imported from a standalone package. This script produces the same artifact
 * shape: the loader envelope is added here, `react` / `react-dom/client` /
 * `react/jsx-runtime` stay external (the running web shell provides them
 * through the loader's `require`), and CSS Modules are resolved at build time
 * with the rule text inlined and injected once at apply time.
 */
import { build, context } from 'esbuild'
import { mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outdir = join(root, 'lib')
const watch = process.argv.includes('--watch')
const { name: packageName } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

if (!watch) rmSync(outdir, { recursive: true, force: true })
mkdirSync(outdir, { recursive: true })

/** Provided by the DSH web shell through the ModuleLoader `require`. */
const RUNTIME_EXTERNALS = ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime']

/** Class names resolved at build time; the rule text is injected at apply time. */
const CSS_MODULE_NAMESPACE = 'css-module-text'
const cssText = new Map()

const cssModulePlugin = {
  name: 'css-module-text',
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /\.module\.css$/ }, (args) => ({
      path: resolve(args.resolveDir, args.path),
      namespace: CSS_MODULE_NAMESPACE,
    }))
    pluginBuild.onLoad({ filter: /.*/, namespace: CSS_MODULE_NAMESPACE }, (args) => {
      const text = readFileSync(args.path, 'utf8')
      cssText.set(args.path, text)
      // A plain class-name map. The upstream preset hashes the names; a stable
      // prefix keeps this fork's styles from colliding with the original
      // plugin's if both bundles ever load on one page.
      const names = [...new Set([...text.matchAll(/\.(-?[_a-zA-Z][\w-]*)/g)].map((m) => m[1]))]
      const entries = names.map((name) => `  ${JSON.stringify(name)}: ${JSON.stringify(`dsm_${name}`)},`).join('\n')
      return { contents: `export default {\n${entries}\n}\n`, loader: 'js' }
    })
  },
}

const shared = {
  bundle: true,
  target: 'es2022',
  logLevel: 'info',
  legalComments: 'none',
  external: RUNTIME_EXTERNALS,
  plugins: [cssModulePlugin],
}

/** Host half: plain ESM, loaded by cordis as the package entry. */
const hostOptions = {
  ...shared,
  platform: 'node',
  format: 'esm',
  entryPoints: [join(root, 'src/index.ts')],
  outfile: join(outdir, 'index.js'),
}

/** Browser half: CJS body, wrapped below. */
const clientOut = join(outdir, 'client.js')
const clientOptions = {
  ...shared,
  platform: 'browser',
  format: 'cjs',
  jsx: 'automatic',
  entryPoints: [join(root, 'src/client/index.ts')],
  outfile: clientOut,
  define: { 'process.env.NODE_ENV': '"production"' },
}

/** Wrap the CJS body in the contract the GUI's __ModuleLoader__ expects. */
function wrapClient() {
  const body = readFileSync(clientOut, 'utf8').replace(/^\/\/# sourceMappingURL=.*$/m, '')
  const indented = body.split('\n').map((line) => (line === '' ? '' : `\t\t${line}`)).join('\n')
  writeFileSync(clientOut, `window.__ModuleLoader__.load({\n\tid: ${JSON.stringify(packageName)},\n\tfactory: (require) => {\n${indented}\n\t}\n});\n`, 'utf8')
}

/** The panel stylesheet, injected once by the client bundle at apply time. */
function writeStyleModule() {
  const text = [...cssText.values()].join('\n')
  writeFileSync(
    join(root, 'src/client/skill-panel.css.ts'),
    `// Generated by scripts/build.mjs — do not edit by hand.\n//\n// The panel stylesheet with the dsm_ class prefix applied, inlined so the\n// browser half ships as one ModuleLoader artifact with no side-car asset route.\nexport const SKILL_PANEL_CSS = ${JSON.stringify(text)}\nexport const SKILL_PANEL_STYLE_ID = ${JSON.stringify(`${packageName}/skill-panel.css`)}\n`,
    'utf8',
  )
  return text.length
}

if (watch) {
  const hostCtx = await context(hostOptions)
  const clientCtx = await context({
    ...clientOptions,
    plugins: [...clientOptions.plugins, {
      name: 'module-loader-wrap',
      setup(pluginBuild) {
        pluginBuild.onEnd((result) => {
          if (result.errors.length > 0) return
          wrapClient()
          const bytes = writeStyleModule()
          console.log(`[watch] rebuilt ${packageName} (${bytes} bytes of CSS inlined)`)
        })
      },
    }],
  })
  await hostCtx.watch()
  await clientCtx.watch()
  console.log(`watching ${packageName}...`)
} else {
  await build(hostOptions)
  await build(clientOptions)
  wrapClient()
  const bytes = writeStyleModule()
  console.log(`built ${packageName}: lib/index.js, lib/client.js (${bytes} bytes of CSS inlined)`)
}
