/**
 * Injects the panel stylesheet once per document.
 *
 * The stylesheet itself is generated by scripts/build.mjs into
 * `skill-panel.css.ts` (see the build script for why CSS Modules are resolved
 * at build time rather than at runtime). This module only owns the <style>
 * tag, so a remount or a second panel instance never stacks duplicate sheets.
 */
import { SKILL_PANEL_CSS, SKILL_PANEL_STYLE_ID } from './skill-panel.css.ts'

/** Inject the panel stylesheet if it is not already in the document. */
export function injectSkillPanelStyles(): void {
  if (typeof document === 'undefined') return
  // Before the first build the generated module ships an empty placeholder, so
  // there is nothing to inject; the length check keeps that a no-op rather than
  // an empty <style> tag.
  if (SKILL_PANEL_CSS.length === 0) return
  if (document.querySelector(`style[data-plugin-css="${SKILL_PANEL_STYLE_ID}"]`) !== null) return
  const tag = document.createElement('style')
  tag.dataset.plugin = 'dsh-skills-manager'
  tag.dataset.pluginCss = SKILL_PANEL_STYLE_ID
  tag.textContent = SKILL_PANEL_CSS
  document.head.appendChild(tag)
}
